### ISSUE TITLE
Can't construct object with class hierarchy

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#102]
``` r
library(R7)
foo <- new_class("foo", properties = list("x" = "numeric"))
foo2 <- new_class("foo2", foo, properties = list("y" = "numeric"))
foo2(x = 1, y = 2)
#> Error in do.call(base::`@`, list(object, name)): trying to get slot "parent" from an object of a basic class ("character") with no slots
```

<sup>Created on 2021-10-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I feel like I'm missing something obvious here, so this might just need a better error.

**Comment by jimhester** [comment]
Did you try writing the constructor explicitly? e.g. https://github.com/RConsortium/OOP-WG/blob/6bfa5bafc593c12e3ad95d35de2e131d03120487/vignettes/case_studies.Rmd#L82-L84

**Comment by hadley** [comment]
Ok, that works:

``` r
library(R7)
foo <- new_class("foo", properties = list("x" = "numeric"))
foo2 <- new_class("foo2", foo, 
  properties = list("y" = "numeric"), 
  constructor = function(x, y) {
    new_object(foo(x = x), y = y) 
  } )
foo2(x = 1, y = 2)
#> <foo2> <foo> <R7_object>
#> @x 1
#> @y 2
```

<sup>Created on 2021-11-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

But ideally, the default constructor should just work, right?

**Comment by jimhester** [comment]
I don't know, maybe? I guess there is some question on how complicated we want the default constructor function to be.

**Comment by hadley** [comment]
I think I can make this work; I'll give it a try. It'd also be nice to eliminate the `...` in order to get better autocomplete.
