### ISSUE TITLE
Prettier syntax for declaring generic, similar to `method<-()`?

### ISSUE THREAD

**Issue by krlmlr** [RConsortium/OOP-WG#104]
I like the

```r
method(mean, ...) <- function(...) {
}
```

syntax because it is so similar to declaring an S3 method or a plain function. How can we support a similar syntax for creating generics? My goal is to avoid `})` at the end of the generic's body, and to avoid overly long `set_generic()` calls spanning multiple lines -- this has been a moderate pain in DBI.

I couldn't get to work

```r
generic(...) <- function(...) {
}
```

because, unlike with methods, the object being assigned to doesn't exist yet.

## Proposal: with a backpipe

Maybe something along the following lines:

``` r
generic <- function(fun, name, signature = NULL) {
  new_generic(name, signature, fun)
}

library(R7)
library(backpipe)
library(magrittr) # still necessary?

mean2 <- generic("mean2") %<% function(x, ..., na.rm = TRUE) {
  method_call()
}

mean2
#> <R7_generic> function (x, ..., na.rm = TRUE)  with 0 methods:
```

<sup>Created on 2021-10-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

## Alternative: turning a function to a generic

With less magic:

``` r
library(R7)

mean2 <- function(x, ..., na.rm = TRUE) {
  method_call()
}
mean2 <- new_generic("mean2", fun = mean2)

mean2
#> <R7_generic> function (x, ..., na.rm = TRUE)  with 0 methods:
```

<sup>Created on 2021-10-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
See https://github.com/RConsortium/OOP-WG/issues/75#issuecomment-950883149 too

**Comment by hadley** [comment]
I'm pretty happy with the current syntax:

```R
mean2 <- new_generic("mean2", "x", function(x, ..., na.rm = TRUE) {
  method_call()
})
```

You have to repeat "mean2" once, but eliminating it is going to require some syntactic gymnastic, and I don't think it's worth it yet.
