### ISSUE TITLE
Method evolution through versioning?

### ISSUE THREAD

**Issue by krlmlr** [RConsortium/OOP-WG#107]
Assuming the following situation:

- Package aa defines a generic `foo()` along with some methods
- Package bb implements more methods for `foo()`
- Package aa decides to change the signature of that generic by adding/renaming/removing/... arguments

I'm proposing a new argument `version = 1` to `new_generic()` and `method<-()`, and a new argument `compat_fun = list()` to `new_generic()`. In this situation, package aa does:

```r
foo_1 <- function(x, ..., new_arg) {
  warning("new_arg discarded")
  method_call("foo", 1, "2021-10-29")
}

foo <- new_generic("foo", version = 2, compat_fun = list(foo_1), fun = function(x, ..., new_arg) {
  method_call()
})
```

Because package bb still registers its method `foo()` with version 1, `method_call()` calls `foo_1()` which is responsible for providing, in its environment, arguments suitable for calling the legacy version of the method. The `method_call("foo", 1)` then dispatches to the legacy method. Package bb can upgrade at its own pace.

The `warning()` could be substituted by a silent signal or by a warning that is triggered only when package bb's own tests are run; perhaps `method_call()` could trigger warnings with increasing severity depending on the date of the version change.

Renaming a generic has also been very challenging in the past. This is a rare situation, but could also be handled by supporting named lists in `compat_fun`:

```r
foo_1 <- function(x, ..., new_arg) {
  warning("foo is now called bar, new_arg discarded")
  method_call("foo", 1, "2021-10-29")
}

foo_2 <- function(x, ..., new_arg) {
  warning("foo is now called bar")
  method_call("foo", 1, "2021-10-30")
}

bar <- new_generic("bar", version = 3, compat_fun = list(foo = foo_1, foo = foo_2), fun = function(x, ..., new_arg) {
  method_call()
})
```

In #7, overloading is described as too complicated. I still think this might be a viable alternative to both solve the problem of generic-method consistency and offer a safe and sane upgrade path for generics.

Related: #85.

**Comment by hadley** [comment]
I think it's to soon to consider specific implementations but I've created meta issue #143 to make sure we remember to think through all the ways that a generic/class might change.
