### ISSUE TITLE
Can a class override properties?

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#113]
```R
foo <- new_class("foo", properties = list(x = "numeric"))
foo2 <- new_class("foo2", parent = foo, properties = list(x = "character"))
```

I think this needs to be an error?

**Comment by jimhester** [comment]
What about if the child property is a subclass of the parent property, should that be allowed? Something like this (ignore the inherent sexism in the example about men only having 'male' names or even there being a set of 'male' names at all)

```r
person <- new_class("person", properties = list(name = "character"))
man <- new_class("man", parent = person, properties = list(name = "male_names"))
```

**Comment by hadley** [comment]
It feels like it would be simpler to express constraints like that in the `validator`?

**Comment by jimhester** [comment]
Ok, as another example in Bioconductor there is a IRange class to represent a numeric range, and a GRange subclass to represent a genomic range (a chromosome + range essentially). I could see cases when a parent class would have a IRange as a position property, and you would want your subclass to use a `GRange` instead for the position property.

**Comment by lawremi** [comment]
What @jimhester mentions definitely comes up in some class hierarchies. It is convenient to allow subclasses to specialize the class of a slot in the parent class.

**Comment by hadley** [comment]
Right, but that still could happen in the `validator`, right?

**Comment by mmaechler** [comment]
> Right, but that still could happen in the `validator`, right?

Yes, but there you'd have to add the code yourself (when creating the validator for the class);  or am I misunderstanding?

Ideally, your very first example would give an error automatically (at class creation) and not just when an instance of that class is validated.   What the class creation functionality could try to do is to check that `GRange` is a subclass if `IRange` (to continue @jimhester 's bioc example.).  At this point, both `IRange` and `GRange` would have to be defined to be used as a class of the properties, and hence their compatibility could be checked automatically.

**Comment by hadley** [comment]
Ok, that makes sense.

**Comment by mmaechler** [comment]
> Are the restrictions on a subclass always greater than or equal to the restrictions on the parent class? ..........
> 
> In other words, when you call `validate(x)`, it should:
> 
>     * Call the `validator` for the class of `x`
> 
>     * Call the `validator` of all parents of the class of `x`

yes, definitely: Validation should happen recursively up the parent chain.  (That's also happening in S4).
 
> And I think `validate()` should probably also check all the property types. Currently we rely on `prop<-` to do the checking, but it would be nice to have something to call that checks validity even if the user has messed with the object using `attr<-`.

Yes,  an explicit call to something like `validObject()` would by default do a full check which would involve all properties be checked.  

However, I don't know in which situations automatic validator() calls are planned to happen; there, it may be important to have "shallow" validation (or even *no* in some cases) for efficiency.

**Comment by hadley** [comment]
Great, I'll make the changes to align the implementation with our shared understanding.

In terms of performance, R7 has a couple of tools to delay validation: `valid_eventually()` and `valid_implicitly()`. They're not very well documented yet, but you can see them on https://rconsortium.github.io/OOP-WG/reference/validate.html.

**Comment by hadley** [comment]
Re-reading this issue and I think everything that needs to be done has been done. You can currently override properties, and it's generally up to you to ensure that your class obeys the LSP.
