### ISSUE TITLE
Access `.data` with a function instead of `@`?

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#114]
I think that would make things more clear since it's not actually a property. (I also wonder if maybe calling it something like `parent` would be more clear)

**Comment by hadley** [comment]
Would also imply renaming `.data` in `new_object` and hence `new_constructor()`.

**Comment by lawremi** [comment]
Agreed. Similar to `methods::S3Part()`.

**Comment by hadley** [comment]
Discussion from meeting:

* Accessor would be something like `???_data()`, and argument name would be `.data`.
* General consensus that we don't need to preserve "virtual" slot.

**Comment by DavisVaughan** [comment]
Possibly could also be `.vector`

**Comment by hadley** [comment]
@DavisVaughan it might not a vector though (e.g. if you're extending a function)
