### ISSUE TITLE
Use dispatch_on instead of signature?

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#116]
What do you think of making `signature` a bit more concrete and renaming it to `dispatch_on`, since it's a vector of argument names that are used for dispatch?  

@mmaechler @lawremi do you think this would be too confusing for existing S4 users?

**Comment by lawremi** [comment]
This sounds like a good change; I think S4 users will quickly catch on. Would we also use that name for the method signature?

**Comment by hadley** [comment]
(Also need to display in the print method for generics)

**Comment by hadley** [comment]
Notes from meeting:

* No need to re-use signature, especially because there's some confusion about it. 
* Would be nice to have a noun, so it's a property of the generic, e.g. `dispatch_args`.
* Seems ok to require `dispatch_args` to be `names(formals(generic))[1:n]` in interest of simplicity and performance.
