### ISSUE TITLE
Common class specification

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#120]
We need a common mechanism for concerting a class specification (e.g. R7 class object, S4 class, S3 class, base type) wherever they're used (as parent, in properties, in class unions, in `method<-`).

We might want some way to be explicit about S3 classes, maybe by providing something like `new_S3_class(class_vector, constructor, validator)`. We could continue to allow a character vector for S3 classes (possibly with a warning), or require an S3 class object.

**Comment by hadley** [comment]
This forces us to be precise about exactly where we can use the various types of object. 

* It seems reasonable to allow anything in properties (since that's just a type check)

* Since unions are used for dispatch (which already supports S3 + S4) and properties (as above), they can allow anything too

* Should we allow R7 classes to extend S4 classes? 

|           | As parent | As property | In union |
|-----------|-----------|-------------|----------|
| R7 class  | x         | x           | x        |
| R7 union  |           | x           | x        |
| S3 class  | x         | x           | x        |
| S4 class  |           | x           | x        |
| Base type | x         | x           | x        |

**Comment by lawremi** [comment]
With regard to extending S4 classes, I think the inherited S4 methods would assume that instances of the subclass were S4 objects, which would break our assumptions, right? For example, `class()` would return a scalar.

**Comment by hadley** [comment]
@lawremi yeah, good point.
