### ISSUE TITLE
Method dispatch for class unions

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#123]
Say we have the following class union:

```R
library(R7)

cls_1 <- new_class("cls_1")
cls_1_1 <- new_class("cls_1_1", cls_1)
cls_2 <- new_class("cls_2")
cls_2_1 <- new_class("cls_2_1", cls_2)

u <- new_union(cls_1_1, cls_2_1)
```

In which order does method dispatch occur?

* Is it breadth-first, i.e. `cls_1_1`, `cls_2_1`, `cls_1`, `cls_2`, `R7_object` ?
* Is it depth-first, i.e. `cls_1_1`, `cls_1`, `R7_object`, `cls_2_1`, `cls_2`

It seems desirable for `R7_object` to come last, so this suggests breadth first?

**Comment by jimhester** [comment]
I think it currently just loops over the classes in each member of the union, which would be depth-first, but I agree breadth first does seem to make the most sense.

**Comment by jimhester** [comment]
Also I don't think there is currently any check for duplicate classes, so R7_object probably currently gets registered twice, with the second registration overwriting the first.

**Comment by lawremi** [comment]
Not sure I understand this question. We wouldn't have an instance of a union, right? Is this for methods with a union in their signature? But wouldn't they have equal affinity for each member of the union?

**Comment by hadley** [comment]
Right, in method dispatch, unions are a shortcut, so instead of writing (e.g.)

```R
method(mean, "integer") <- function(x) sum(x) / length(x)
method(mean, "double") <- function(x) sum(x) / length(x)
```

You can write:

```R
numeric <- new_union("integer", "double")
method(mean, numeric) <- function(x) sum(x) / length(x)
```

But I guess the problem only occurs if you mix dispatch on unions with dispatch on classes, so we might be able resolve this by warning when you override an existing method?

**Comment by lawremi** [comment]
Or we just define a rule that a method for a member of a union takes precedence over a method for that union.

**Comment by mmaechler** [comment]
> Or we just define a rule that a method for a member of a union takes precedence over a method for that union.
Yes, this would really intuitive, notably for people who already know the traditional S3 and S4 group methods.

**Comment by hadley** [comment]
Ok, I'll have to think about how to implement that; currently defining a method for a union just defines methods for the individual classes. 

That also raises the general question of what happens when you override an existing method. Currently it is silently overridden — that's probably what you want for interactive development, but not what you want when loading multiple packages.

``` r
library(R7)

foo <- new_class("foo")
bar <- new_generic("bar", signature = "x")

method(bar, foo) <- function(x, ...) 1
method(bar, foo) <- function(x, ...) 2

bar(foo())
#> [1] 2
```

<sup>Created on 2021-12-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ltierney** [comment]
On Mon, 13 Dec 2021, Hadley Wickham wrote:

> 
> Ok, I'll have to think about how to implement that; currently defining a
> method for a union just defines methods for the individual classes.
> 
> That also raises the general question of what happens when you override an
> existing method. Currently it is silently overridden — that's probably what
> you want for interactive development, but not what you want when loading
> multiple packages.

Dylan used to have the concept of marking various things as
'sealed'. That may be worth considering.

> 
> library(R7)
> 
> foo <- new_class("foo")
> bar <- new_generic("bar", signature = "x")
> 
> method(bar, foo) <- function(x, ...) 1
> method(bar, foo) <- function(x, ...) 2
> 
> bar(foo())
> #> [1] 2
> 
> Created on 2021-12-13 by the reprex package (v2.0.1)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.[AA55UVETDP6UWUAXEPMC7IDUQYOAVA5CNFSM5H6YBGDKYY3PNVWWK3TUL52HS4DFVREXG43VMV
> BW63LNMVXHJKTDN5WW2ZLOORPWSZGOHMVL5ZY.gif]
> 
> 
>

-- 
Luke Tierney
Ralph E. Wareham Professor of Mathematical Sciences
University of Iowa                  Phone:             319-335-3386
Department of Statistics and        Fax:               319-335-3017
    Actuarial Science
241 Schaeffer Hall                  email:   ***@***.***
Iowa City, IA 52242                 WWW:  http://www.stat.uiowa.edu

**Comment by hadley** [comment]
In R7, method dispatch for unions is handled at method registration time, rather than at method dispatch time like S4. I think this approach is a bit simpler because it means that creating a R7 union does not affect the class hierarchy of existing R7 classes in the way that creating a S4 union does. This means that we can't prefer explicit classes over unions in general.

For now, I've added a message so that you at least know when you're overriding a method, and we can revisit sealing in the future.
