### ISSUE TITLE
Override behaviour when calling, using in if statement, or in a for loop

### ISSUE THREAD

**Issue by t-kalinowski** [RConsortium/OOP-WG#127]
In a Python class it is possible to define a dunder method named `__call__`, which becomes the method that is invoked when an instance of the class is called. This enables some interesting API design patterns. This is heavily used in, for example, keras and many other deep learning libraries.

From a implementation standpoint a hacky way would be to overload R closures (akin to what `ecdf()` does), but if new syntax is on the table then of course something much more elegant is possible.

**Comment by hadley** [comment]
I've contemplated this in the past, but at the end of the day, I just can't convince myself that the extra effort is worth it compared to just extending a function. Basically, I don't think overloading closures is hacky.

**Comment by t-kalinowski** [comment]
It would seem I've [nerd-sniped](https://xkcd.com/356/) myself. I got curious and sketched out what it might look like if class instances were callable.

Is it hacky? ¯\\_(ツ)_/¯ 
It certainly could be much simpler if environments were callable (not to mention faster/lighter if each instance wasn't constructing a fresh copy of all the methods)

Here is the sketch: [t-kalinowski/R9000](https://github.com/t-kalinowski/R9000)

I must admit I'm partially motivated by the fact that, as maintainer of the tensorflow/keras R packages, I spend a lot of time at the python <-> R interface and acutely feel the absence of python features from R (and vice-versa, I should add).

Callable class instances are one such missing feature. Some others that come to mind are:
  + objects with a `__bool__` method can be used directly in `if`
  + objects with `__iter__` and `__next__` methods can be used directly in `for`
  + objects with `__enter__` and `__exit__` methods can be used in `with`
  
Of course there are trivial (or not-so-trivial) ways to achieve equivalent outcomes in R, but they range from unergonomic to extremely esoteric. And this mismatch unfortunately means that users interested in porting some python code to R need deep knowledge of both languages.

In any case, I realize this is perhaps a niche motivation. Please feel free to close the issue if there is no interest.

**Comment by hadley** [comment]
For callables, would need to think about the function namespacing (lisp-2) issue.

**Comment by hadley** [comment]
Now part of #222
