### ISSUE TITLE
Should properties have a default value?

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#139]
This would be used by the default constructor when the property is not supplied. 

If properties can have a default value, should it be supplied automatically? i.e. if the property is an R7 or S4 class, it could call the default constructor. This would have the advantage that you can always easily initialise a class>

**Comment by lawremi** [comment]
This makes sense to me. The methods package initializes slots by just calling `new(class)`, i.e., that is how it generates the default prototype.

**Comment by hadley** [comment]
This means we'd need to add constructors for non-vector base types (e.g. function), and `s3_class()` would need to gain a constructor argument. That would probably push us further towards pre-defining some key s3 classes provided by base R. I think this is likely to look something like this:

```R
s3_factor <- s3_class("factor", factor)
s3_data_frame <- s3_class("data.frame", data.frame)

# Needed because S3 functions error when called without arguments
s3_ordered <- s3_class(c("factor", "ordered"), function(x = character(), ...) ordered(x, ...))
s3_date <- s3_class("Date", function(x = integer()) .Date(x))
```

If your class defines a validator and it fails with the default property values, it'd be your responsibility to either adjust the property defaults or override the constructor.

Should we make the default a function? It seems like it would be convenient to do something like this:

```R
new_property("created_at", s3_date, default = function() Sys.Date())
```

**Comment by lawremi** [comment]
For unions, the methods package uses the prototype of the first member of the union (where "NULL" is always considered first if present). 

In my experience, it's a lot more common to want a constant as the default, so a function might be too complex. It's fairly straightforward to achieve the same effect in the class constructor. That has the minor added benefit of putting all code executed during object instantiation in one place.

**Comment by hadley** [comment]
Makes sense. What should `default = NULL` do? Does it make `NULL` the default, or does it use the default value from the type?

**Comment by lawremi** [comment]
It would be `NULL`. The automatic default would only apply if no default is provided.

**Comment by hadley** [comment]
Ah you're thinking the behaviour is conditional on whether or not the argument is `missing()`? I'm not a big fan of that sort of interface, but maybe it works ok here.

**Comment by hadley** [comment]
Somewhat related to this discussion, but in the course of working on this code I realised that the R7 wrapper of the environment base class used `new.env(parent = emptyenv())`, but this wasn't wrapped in a function so every instance of the class got the same environment.
