### ISSUE TITLE
typeof() and isS4() are inconsistent

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#151]
``` r
library(R7)

foo <- new_class("Foo")()
isS4(foo)
#> [1] FALSE
typeof(foo)
#> [1] "S4"
```

<sup>Created on 2022-02-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
@ltierney currently we create the "base" R7 object with:

```c
SEXP R7_object_() {
  return Rf_allocSExp(S4SXP);
}
```

Should we be doing something different here?

Or does this inconsistency not matter?

**Comment by hadley** [comment]
Or is this correct? `typeof(x) == "S4"` implies that we're using the S4 object type while `isS4(x) == FALSE` implies that we're not using the S4 object system.

**Comment by lawremi** [comment]
Seems consistent to me. `isS4()` checks the object bit, which we are not setting.

**Comment by hadley** [comment]
Ok, great.
