### ISSUE TITLE
[design] when to validate objects

### ISSUE THREAD

**Issue by wlandau** [RConsortium/OOP-WG#17]
Thanks for drafting the design document, @lawremi.

Early on, you wrote:

> Initializing an instance of a class will:
> 
> 1. Create the prototype, by either adding the class label to the parent instance or constructing an empty S4SXP,
> 2. Merge any given property values, and
> 3. Validate and return the result.

I like that we have a dedicated place for validation, but perhaps we should touch base about when we want it to happen. Just concerned about the potential overhead of validating on every initialization.

**Comment by mmaechler** [comment]
Good point.  Has been quite relevant for S4, too.  
I don't know the pre-history, but IIRC, it was important that you could incrementally build an object in a way that validation would not yet happen during the build up.
