### ISSUE TITLE
Does method registration actually work for packages?

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#184]
`method()<-` will be called at build time so if the generic is not in the package, it will be modified and then discarded?

**Comment by lawremi** [comment]
Wouldn't it still be in the package namespace if a new object was assigned? Then it is a matter of merging the method lists into the original generic after the namespace is loaded.

**Comment by hadley** [comment]
It also occurred to me that if we implemented #50, then we could use deserialization to automatically register methods onto the appropriate generic.

**Comment by hadley** [comment]
Oh and `@` won't work either unless you import it (and re-export it if you want your users to be able to use).

**Comment by hadley** [comment]
For now, I'll just recommend that you always use external generics (not just for suggested packages).

**Comment by hadley** [comment]
Oh and we need to make sure that you can actually call an external generic so that you can use it during testing etc.
