### ISSUE TITLE
inheritance + check functions

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#193]
Need equivalent of `is()`/`inherits()`, along with a helper that asserts that an object is of a class (extracting code out of the property checkers). Implementation already exists in `class_inherits()`; just needs a better name.

**Comment by hadley** [comment]
`instance` (from Dylan) is another idea.

**Comment by lawremi** [comment]
Would `is/inherits()` not work already? I thought we were just using the S3 class vector approach.

**Comment by lawremi** [comment]
What do you mean by a vector of `NA`? Isn't the vector type a separate concept from missingness?

**Comment by hadley** [comment]
You could use `inherits()` currently, but you'd have to get the vector of class names somehow. I think you want some function where you can do:

```R
foo <- new_class("foo")
x <- foo()

is_a(x, foo)
#> [1] TRUE

is_a(1, foo)
#> [1] FALSE
```

The `NA` case, I think, is needed for property checking of base types, since currently we have:

``` r
library(R7)
foo <- new_class("foo", properties = list(x = character))
foo(x = NA)
#> Error: <foo> object properties are invalid:
#> - @x must be <character>, not <logical>
```

<sup>Created on 2022-03-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

which I think is a bit unappealing. Maybe that needs to be handled elsewhere, but property type checking currently uses the internal `class_inherits()`, which is what I would imagine would power `is_a()`.

**Comment by lawremi** [comment]
Ok, so `is_a()` would accept the class object instead of the class name, got it.

I'd prefer to handle the `NA` case as a convenience during construction, while ensuring that properties are always of the correct type, even if every value is `NA`.
