### ISSUE TITLE
[design] symbols for syntactic sugar

### ISSUE THREAD

**Issue by wlandau** [RConsortium/OOP-WG#20]
When it comes to syntactic sugar, I have a personal preference to overload operators that users are likely to already be familiar with. For example, although `@` has precedent from S4, I rarely see it used elsewhere. Is there anything that prevents us from choosing the more ubiquitous `$`? Property values feel a lot like list elements to me.

**Comment by hadley** [comment]
`y@x` is really a shortcut for `attr(y, "x")` so I think it makes sense to continue using it. In general, using `$` is challenging because it makes it hard to provide a `$` method.

**Comment by wlandau** [comment]
Fair enough. #21 actually makes me feel better about @ because it’s consistently used instead of $, so I don’t have to think about when to use which.

**Comment by ltierney** [comment]
`y@x` currently only works for S4 objects. That could be changed.

**Comment by lawremi** [comment]
Let's stick with `y@x`.
