### ISSUE TITLE
Print method when `parent = "list"` seems suboptimal

### ISSUE THREAD

**Issue by DavisVaughan** [RConsortium/OOP-WG#205]
``` r
library(R7)

foo <- new_class("foo", "list")
obj <- foo(list(x = 1, y = 1:5))
obj
#> <foo>List of 2
#>  .. $ : num 1
#>  .. $ : int [1:5] 1 2 3 4 5

# can't see the names x/y like you can here
str(list(x = 1, y = 1:5))
#> List of 2
#>  $ x: num 1
#>  $ y: int [1:5] 1 2 3 4 5
```

<sup>Created on 2022-03-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
Oh because we strip all the attributes in the print method, including the names.

**Comment by DavisVaughan** [comment]
Should the type name also be on its own line?

i.e. this is weird

```r
#> <foo>List of 2
#>  $ x: num 1
#>  $ y: int [1:5] 1 2 3 4 5
```

This seems ok

```r
#> <foo>
#> List of 2
#>  $ x: num 1
#>  $ y: int [1:5] 1 2 3 4 5
```

And this wouldn't look too bad for other types:

```r
library(R7)

foo <- new_class("foo", "integer")
obj <- foo(1:5)
obj

# current
#> <foo> int [1:5] 1 2 3 4 5

# maybe
#> <foo> 
#> int [1:5] 1 2 3 4 5
```

**Comment by hadley** [comment]
I think it should be on the same line, but it needs a space. And the elements should line up with the propreties

``` r
library(R7)

foo <- new_class("foo", "list", properties = list(x = "integer", y = "integer"))
obj <- foo(list(x = 1, y = 1:5))
obj
#> <foo> List of 2
#> $ x : num 1
#> $ y : int [1:5] 1 2 3 4 5
#> @ x:  int(0) 
#> @ y:  int(0)
```

<sup>Created on 2022-03-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
Some of the constraints are we want to keep skating around the outside of `str()` to avoid reimplementing too much ourselves.
