### ISSUE TITLE
Dispatch using dollar, not at

### ISSUE THREAD

**Issue by stefanoborini** [RConsortium/OOP-WG#210]
If you dispatch with a different operator, now any code that relies on the same operator will have to differentiate if it's receiving an actual class instance or its serialisation.

Example: suppose I have a function that receives an object. This function may have to extract data from the object properties. I might want to pass the object directly, which is fine, but if this function then needs to be called in a separate process, I will have to serialise the object to e.g. an environment, and marshal it to the function executing on the separate process. The function will now receive an environment. If you use the dollar, the function won't know the difference. If the operator is different, now it will have to use the at for interacting with the object, and the dollar for interacting with the environment. 

There's _absolutely_ no need to complicate the dispatch with a different operator. Stick to the established standard.

**Comment by lawremi** [comment]
Properties are different from elements of a collection. `$()` is for accessing collection elements (of a list or environment). Properties implement the representation of an object. Using a different syntax enables a class to extend list or environment with properties distinct from the collection itself.

**Comment by stefanoborini** [comment]
@lawremi all other languages have one and only one dispatch operator for methods and properties. Why R must have two? I say again, this will complicate the serialisation to an environment and force to differentiate the lookup of the same entity on an environment instead of an object. It will also make it hard to explain to people the difference between @, $ and :: when you teach it.

**Comment by stefanoborini** [comment]
On the topic, I implemented this exact strategy and use dollar to intercept and redirect properties that map to shiny reactiveValues(). I use dollar for everything. If the property is marked as property in the metaclass, it will use the reactiveValues(), otherwise the standard lookup in the R6 associated environment.
