### ISSUE TITLE
Accessing a missing name should throw an error, not return NULL

### ISSUE THREAD

**Issue by stefanoborini** [RConsortium/OOP-WG#211]
Don't know if this is already implemented, but please, don't return NULL for accessing unexistent names. It's absolutely stupid and leads to confusing error messages and late-found bugs.

if I call object$mystypedmethodname() I want to get an error "mystypedmethodname does not exist", not "Error: attempt to apply non-function". Same for properties. If I ask for foo$myvalue and I never specified myvalue, I want an error, not a NULL that will start scouting around my code and fail 300 lines later with no chance of finding the actual point where the problem originally is.

**Comment by hadley** [comment]
Not sure what you're talking about? `@` already complains about properties that don't exist:

``` r
library(R7)

myclass <- new_class("myclass", properties = list(x = numeric))
obj <- myclass(x = 1)
obj@x
#> [1] 1
obj@y
#> Error in prop(object, name): Can't find property <myclass>@y
```

<sup>Created on 2022-03-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by stefanoborini** [comment]
good!
