### ISSUE TITLE
Consider a common prefix?

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#22]
I think it would be worth considering if a common prefix would be useful, as a way to very clearly signal what object system code is using, e.g.:

* `s7_class()` instead of `classObject()`
* `s7_methods()` to avoid clash with `methods()`
* `s7_properties()` for consistency

(Just using s7 as placeholder since the goal is S3 + S4)

**Comment by lawremi** [comment]
If this is a fully compatible extension of S3, I'd want to avoid making it sound like something totally distinct. For example, `class()` works just fine on these objects, makes all S3 generics just work, and is a simple way of showing the class hierarchy.  `classObject()` makes the difference explicit. Ideally we could make `methods()` behave in a backwards compatible way also. Perhaps all it would take is for `$.MethodsFunction()` to get a specific method definition.

**Comment by hadley** [comment]
Yeah, that makes sense.
