### ISSUE TITLE
S4SXP objects without the S4 object flag

### ISSUE THREAD

**Issue by traversc** [RConsortium/OOP-WG#220]
I believe this goes against the documentation for R internals. Specifically, these sections:

> 1.1.1 SEXPTYPEs
> S4SXP	S4 classes not of simple type
> ...
> 1.12.1 Representation of S4 objects
> S4 objects can be of any SEXPTYPE. They are either an object of a simple type (such as an atomic vector or function) 
> with S4 class information or of type S4SXP. In all cases, the ‘S4 bit’ (bit 4 of the ‘general purpose’ field) is set, and can 
> be tested by the macro/function IS_S4_OBJECT.

Unfortunately, setting the flag right after object creation (using `SET_S4_OBJECT`) does give an ugly warning:

```
Warning message:
In class(object) <- setdiff(class_dispatch(class), "ANY") :
  Setting class(x) to multiple strings ("range", "R7_object", ...); result will no longer be an S4 object
```

But there are other solutions, e.g. circumventing the warning by setting the flag after assigning class names.

**Comment by hadley** [comment]
We discussed this in #151 and decided that the current behaviour is ok, and might become a cheap way to distinguish R7 objects in C code.
