### ISSUE TITLE
Default constructor could take instance as first argument

### ISSUE THREAD

**Issue by lawremi** [RConsortium/OOP-WG#229]
`methods::initialize()` takes an instance of the class (or subclass, in which case extra slots are dropped) as the first argument, and named arguments specify the slot values, overriding those of the first argument.  This behavior has proven convenient for creating derivative objects. I wonder if the default constructor could behave similarly. This would often force property arguments to be named in calls to the constructor, but that at least benefits clarity.

I wonder though whether this is a feature that most benefits implementations, and so should instead be supported by a different function, like `set_props()`, which would just be a simple wrapper around `props<-()`.

**Comment by hadley** [comment]
You can do this currently with `` `props<-`(obj, x = 1, y = 2) `` but that's an unpleasant syntax.

**Comment by mmaechler** [comment]
Hmm,  I never got why `set_props()` was needed when we have  `props(obj)  <-  <propslist>`
and indeed the RHS could be a simple list ?? 
Using  `set_*()`  is really "S4-ish" and "non-R-ish"  in comparison  with  `props(.) <- ..`
 {yes, I must have missed something}

**Comment by hadley** [comment]
@mmaechler sometimes you want to create a modified copy of the object, rather than modifying in place.
