### ISSUE TITLE
Remove method list from class object

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#23]
I'd suggest removing the method list from the class object, at least for an initial round of discussion. I think it makes it seems  like you're proposing a bigger change (from generic function OO to encapsulated OO) than I think you are, and it seems like it might be distracting at this point in the discussions. I also don't love the idea of having a mutable object here as it would make cleanly detaching packages even more complex than it is currently.

**Comment by lawremi** [comment]
I may have been jumping ahead to implementation. It would help to discuss how we see methods being defined and registered. Presumably, we would continue to use the existing S3 method registry, except somehow supporting nested dispatch. Would we still have functions assigned to symbols with the pattern `generic.class`? If so, would it make sense to simply define methods by assigning them to that symbol, as we do now for S3 methods? Would we use the pattern `generic.class1.class2` for nesting?
