### ISSUE TITLE
R session aborts when a generics `fun` overwrites a supplied argument

### ISSUE THREAD

**Issue by KaiAragaki** [RConsortium/OOP-WG#254]
Apologies if this should be directed to the RStudio repo.

Reprex:

```
library(R7)

my_generic <- new_generic("my_generic", "x", function(x) {
  x <- x
  R7_dispatch()
})

my_method <- method(my_generic, class_character) <- function(x) {
  x
}

my_generic("x")

```

This is fine though:

```
my_generic <- new_generic("my_generic", "x", function(x) {
  ex <- x
  R7_dispatch()
})

my_generic("x")
```

RStudio version: 2022.07.2+576 (2022.07.2+576)
OS: macOS 12.6

**Comment by hadley** [comment]
What do you mean by crashes?

**Comment by KaiAragaki** [comment]
Sorry - not RStudio, but rather the R Session. I'll change the title. See image for details.

Reproduced on Linux (Mint 20.3 Cinnamon), which screams before it dies (see console in background)

![image](https://user-images.githubusercontent.com/7370516/195610256-a7f9e054-4a26-4017-b1e0-8b3ad194dd16.png)

**Comment by hadley** [comment]
Updated reprex:

``` r
library(S7)

my_generic <- new_generic("my_generic", "x", function(x) {
  x <- x
  S7_dispatch()
})

method(my_generic, class_character) <- function(x) {
  x
}

my_generic("x")
```

I also see the crash

**Comment by hadley** [comment]
Error is coming from https://github.com/RConsortium/OOP-WG/blob/abstract-parent-readonly-property/src/method-dispatch.c#L133, presumably because this isn't an unevaluated promised.
