### ISSUE TITLE
Child objects cannot have abstract parents

### ISSUE THREAD

**Issue by jl5000** [RConsortium/OOP-WG#258]
Unless I'm misunderstanding what abstract classes are, I thought objects with abstract parent classes should be able to be created?

``` r
library(R7)

parent = new_class("new_class", properties = list(prop1 = class_character))
child = new_class("child", parent = parent)
grandchild = new_class("grandchild", parent = child)

grandchild()
#> <grandchild>
#>  @ prop1: chr(0)

parent = new_class("new_class", abstract = TRUE, properties = list(prop1 = class_character))
child = new_class("child", parent = parent, abstract = TRUE)
grandchild = new_class("grandchild", parent = child)

grandchild()
#> Error: <grandchild> object properties are invalid:
#> - @prop1 must be <character>, not <NULL>
```

<sup>Created on 2022-11-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jtlandis** [comment]
There seems to be a small typo, I noticed this issue earlier today as well.

**Comment by hadley** [comment]
Looks like something is going wrong with property setting/inheritance:

``` r
library(R7)

parent <- new_class(
  "new_class",
  abstract = TRUE,
  properties = list(prop1 = class_character)
)

child <- new_class("child", parent = parent)
child()
#> Error: <child> object properties are invalid:
#> - @prop1 must be <character>, not <NULL>
child(prop1 = "x")
#> Error: <child> object properties are invalid:
#> - @prop1 must be <character>, not <NULL>
```

<sup>Created on 2022-11-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jtlandis** [comment]
This issue is a typo that affects how the constructor call is formulated, attaching arguments as the second element of the list instead of binding with `c()`.

``` r
library(R7)

parent <- new_class(
  "new_class",
  abstract = TRUE,
  properties = list(prop1 = class_character)
)

child <- new_class("child", parent = parent)
child@constructor
#> function (prop1 = class_missing) 
#> new_object(R7_object(), list(prop1 = prop1))
#> <environment: namespace:R7>
```

<sup>Created on 2022-11-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The following change fixed the issue

![Screenshot from 2022-11-15 16-34-28](https://user-images.githubusercontent.com/30324172/202030026-f896530e-3690-40e0-b2f2-f98329e0675d.png)

**Comment by hadley** [comment]
@jtlandis would you like to do a PR?

**Comment by jl5000** [comment]
I think it's #257.

**Comment by jl5000** [comment]
This is probably related, but there's also an issue with calculated properties of child objects of abstract parents:

``` r
library(R7)

parent <- new_class("parent", abstract = TRUE,
                    properties = list(x = class_numeric))

myclass <- new_class("myclass", parent = parent,
                     properties = list(
                       y = new_property(class_numeric,
                                        getter = function(self) self@x + 1))
)

myclass(1)
#> Error: Can't set read-only property <myclass>@y
```

<sup>Created on 2022-11-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
