### ISSUE TITLE
Can't set property default to `NULL`

### ISSUE THREAD

**Issue by jl5000** [RConsortium/OOP-WG#259]
I'm trying to define some properties which are based on a custom class. Whilst I can do this, I can't figure out a way to make the property optional. In the reprex below, the `potentially_missing` class must contain an x value. However, in `myclass` I can't omit the `y` argument since it attempts to create an empty `potentially_missing` object. I've tried unioning it with `class_missing` but it doesn't seem to make a difference. How do I do something like this?

``` r
library(R7)

potentially_missing <- new_class("potentially_missing",
                                 properties = list(
                                   x = class_numeric
                                 ),
                                 validator = function(self){
                                   if(length(self@x) == 0) return("Error")
                                 }
)

potentially_missing()
#> Error: <potentially_missing> object is invalid:
#> - Error

myclass <- new_class("myclass",
                     properties = list(
                       x = new_property(new_union(potentially_missing, class_missing)),
                       y = new_property(new_union(potentially_missing, class_missing))
                     )
)

myclass(x = potentially_missing(1))
#> Error: <potentially_missing> object is invalid:
#> - Error
```

<sup>Created on 2022-11-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment]
I think ideally you'd do something like this:

```R
myclass <- new_class("myclass",
  properties = list(
    x = new_property(new_union(potentially_missing, NULL), default = NULL),
    y = new_property(new_union(potentially_missing, NULL), default = NULL)
  )
)

myclass(x = potentially_missing(1))
```

But that currently doesn't work because `default = NULL` means use to use the default constructor.

For now, you can work around the problem by making `NULL` the first element of the union:

```R
myclass <- new_class("myclass",
  properties = list(
    x = new_property(new_union(NULL, potentially_missing)),
    y = new_property(new_union(NULL, potentially_missing))
  )
)

myclass(x = potentially_missing(1))
```

**Comment by jl5000** [comment]
Thank you. Does that mean I'm misinterpreting what class_missing is for?

**Comment by hadley** [comment]
It's currently only use for dispatch.
