### ISSUE TITLE
How does constructor find initializer?

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#26]
I think these are the four options that we discussed in the call:

```R
function(x, y) Range@new(x = x, y = y)

# constructor function gets class object as first argument
# user facing constructor would need to drop this automatically
function(class, x, y) class@new(x = x, y = y)

# .class injected into enclosing environment
function(x, y) .class@new(x = x, y = y)

# newObject() looks for .class in enclosing scope
function(x, y) newObject(x = x, y = y)
```

**Comment by lawremi** [comment]
Thanks. The last solution with `newObject()` seems simplest. The first introduce a weird difference in the formals, and the second relies on a hidden symbol, which is tough to document. There is already precedent with `NextMethod()`, `callNextMethod()`, and `callGeneric()`.

**Comment by hadley** [comment]
The last solution also relies on some hidden state, but at least it's completely hidden. Would need to make sure it fails with a useful error when used outside of a constructor.

**Comment by mmaechler** [comment]
I've also immediately liked the `newObject(..)` solution the most.   ((and replaced some `start, end` by `x, y` in your code chunk))

**Comment by hadley** [comment]
Since that option seems to be the most popular, I made #30 to show how it would affect the design doc.
