### ISSUE TITLE
Constructor Vs Initialize

### ISSUE THREAD

**Issue by jl5000** [RConsortium/OOP-WG#260]
I understand that there is the capability to define our own constructor function. In my case, I have no need to modify this (nor would I want to), but I would like to run some code immediately after the object has been constructed. Would this be an opportunity to distinguish between constructor code and initialization code? Perhaps an initialization function as an additional argument?

**Comment by hadley** [comment]
I think we currently want to keep this part of the design as simple as possible, as we don't think the need to customise the `constructor` will be very common.
