### ISSUE TITLE
Class analogue to `purrr::partial()`

### ISSUE THREAD

**Issue by jl5000** [RConsortium/OOP-WG#261]
I'd like to create a special case of a class, where certain properties are pre-set and cannot be changed. Do I need to use a constructor for this? I've searched high and low for an example but I cannot find one anywhere. This is my best effort:

``` r
library(R7)
  
parent <- new_class("parent",
                    properties = list(
                      x = class_character,
                      y = class_character
                    ))

partial <- new_class("partial", parent = parent,
                     constructor = function(x, y){
                       new_object(parent, x, y = "preset")
                     })

test <- partial()
#> Error in new_object(parent, x, y = "preset"): argument "x" is missing, with no default
```

<sup>Created on 2022-11-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

(P.S. I get a bit nervous posting these ideas, as I'm not sure it's the best place for them. Please let me know if it's inappropriate)

**Comment by hadley** [comment]
Just use a regular function?

It's fine to post here, since there's no where else.

**Comment by hadley** [comment]
Such is life 😄 

But if that's what you're worried about, you could just use `purrr::partial()`.
