### ISSUE TITLE
Subsetting R7 objects

### ISSUE THREAD

**Issue by jl5000** [RConsortium/OOP-WG#263]
Sorry for what may be a dumb question, but I'm having trouble extracting properties from an R7 object, when the property name needs to be evaluated:

``` r
library(R7)

myclass <- new_class("myclass",
                     properties = list(prop1 = class_character))

x <- myclass("test")

x@prop1 # Normal subsetting with @
#> [1] "test"
x[["prop1"]] # Subsetting with [[ doesn't work
#> Error: R7 objects are not subsettable.
`@`(x, "prop1") # Using @ as a function
#> [1] "test"
`@`(x, paste0("prop", 1)) # Need to evaluate 2nd argument
#> Error in if (!prop_exists(object, name)) {: the condition has length > 1
`@`(x, eval(paste0("prop", 1)))
#> Error in if (!prop_exists(object, name)) {: the condition has length > 1
```

<sup>Created on 2022-11-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Some documentation on how to do this would be useful as `[[` doesn't work.

**Comment by hadley** [comment]
You need `prop()`. It's documented with `@`: https://rconsortium.github.io/OOP-WG/reference/prop.html
