### ISSUE TITLE
Properties vs object data

### ISSUE THREAD

**Issue by wlandau** [RConsortium/OOP-WG#28]
In S4, the slots have the data. In S3, the object *is* the data. It seems like we're planning to do both with this system. If we like this, when should something be a property and when should it be part of the object?

Propertyless objects are easier to understand, but property-only objects could give us [record-style objects](https://vctrs.r-lib.org/articles/s3-vector.html#record-style-objects) almost for free. 

I guess it would be possible for the user to choose either extreme when the situation calls for it. Not sure if there's anything actionable other than establishing usage patterns and recommendations. I think it's worth pondering even at this early stage.

**Comment by hadley** [comment]
I don't quite understand what you're getting here — in S4, the data lives in attributes (just called slots) like S3.

**Comment by wlandau** [comment]
I was just reflecting out loud on how attributes in S3 need not contain all the data (and tend to act more like metadata) whereas all the data in S4 always live in attributes. Because the new system will be capable of both S3-like and S4-like data management, I was wondering if we needed to do anything special to establish reasonable best practices. But given how much has already been written about S3 and S4, perhaps this won't be difficult and is not worth an issue.

**Comment by mmaechler** [comment]
@hadley : This (about S4) is not quite true.  You can have S4 objects with slots and you can have "direct" ones.  They now do show with a ".Data" slot, but that's more an artefact, than a concept..  Even if 98% do have slots, the others are really important too:

```r
> brob <- setClass("brob", contains="numeric")
> ## "brob" is class name and brob() is constructor
> (bp <- brob(pi))
An object of class "brob"
[1] 3.141593
> stopifnot(exprs = {
+   isS4(bp)      
+   is.numeric(bp)
+   is.atomic (bp)
+ }) # so it's basically *not* an object with slots
> str(bp)
Formal class 'brob' [package ".GlobalEnv"] with 1 slot
  ..@ .Data: num 3.14
> dput(bp)
new("brob", .Data = 3.14159265358979)
> .Internal(inspect(bp))
@12e02560 14 REALSXP g0c1 [OBJ,REF(20),S4,gp=0x10,ATT] (len=1, tl=0) 3.14159
ATTRIB:
  @12dfef48 02 LISTSXP g0c0 [REF(1)] 
    TAG: @1fde610 01 SYMSXP g0c0 [MARK,REF(65535),LCK,gp=0x4000] "class" (has value)
    @12b91cb8 16 STRSXP g0c1 [REF(65535),ATT] (len=1, tl=0)
      @104a6450 09 CHARSXP g0c1 [REF(281),gp=0x61,ATT] [ASCII] [cached] "brob"
    ATTRIB:
      @12b94cc0 02 LISTSXP g0c0 [REF(1)] 
	TAG: @1fddff0 01 SYMSXP g0c0 [MARK,REF(65535)] "package"
	@5cdd4e8 16 STRSXP g0c1 [MARK,REF(65535)] (len=1, tl=0)
	  @2029d48 09 CHARSXP g0c2 [MARK,REF(1645),gp=0x61] [ASCII] [cached] ".GlobalEnv"
> 
```

**Comment by mmaechler** [comment]
> I don't quite understand what you're getting here — in S4, the data lives in attributes (just called slots) like S3.

John Chambers (I think) would strongly object:  He has always emphasized that is just an implementation detail that slots were implemented via attributes ..

**Comment by hadley** [comment]
@mmaechler agreed; I was making a generalisation for the purposes of keeping the discussion at the design level.
