### ISSUE TITLE
Extending `@` beyond `S7`

### ISSUE THREAD

**Issue by jtlandis** [RConsortium/OOP-WG#282]
The goal for this post is to start a discussion around the `@` as syntax in R moving forward. While I know this isn't exactly the best place to discuss feature requests involving R, I figured since the end goal is for `S7` to be integrated into `base` sometime in the future it may be worth talking about.

Currently, `@` only works in base R for `S4` like objects. While S4 likes to dub values accessed or set through `@` as "slots", under the hood, they are a really the attributes of the object.

`S7` mimics the convenience of `@` and dubs values on its objects as "properties", which are again, attributes. `S7` gets around using `@` by exporting its own function.

    `@` <- function(object, name) {
      if (inherits(object, "R7_object")) {
       name <- as.character(substitute(name))
        prop(object, name)
      } else {
        name <- substitute(name)
        do.call(base::`@`, list(object, name))
      }
    }

I think it would benefit R moving forward if we simply allowed ALL attributes to be accessed via `@`, regardless if its a base type, `S3`, `S4` or `S7`, etc.

This change by itself would not enable `S7` - as `S7` also aims to allow `getter` and `setter` functions in place of attributes, which is mostly enabled through their `prop` and `prop<-` functions. I imagine that when `S7` is merged to `base`, the plan is to move all of the `prop` and `prop<-` magic inside the `.Primitive("@")` implementation which will just branch.

Maybe there should also be support for `@.<class>` and `@<-.<class>`?

**Comment by lawremi** [comment]
We intend to make this change eventually, downstream of getting S7 on CRAN.
