### ISSUE TITLE
more granular type on class properties 

### ISSUE THREAD

**Issue by Sage0614** [RConsortium/OOP-WG#284]
I have question about how to have a more specific type defined in the class properties, and I think it might worth an article in the official documentation since many people would need it:

Suppose I would like a new class which is a math object, and the underlying data is stored in the sparse matrix format in Matrix package

`math_obj <- new_class('math_obj',properties = list(
  data = new_property(
    class_any, ## I want a sparse matrix here
  )
))`

seem best I can do right now is to define the property as class_any, and defer the type check to validator, is there any more concise way in doing this?

**Comment by lawremi** [comment]
You should be able to pass the S4 class object corresponding to the class from the Matrix package. In other words, something like `getClass("dgCMatrix")`.

**Comment by Sage0614** [comment]
Thanks a lot, this is not a documented behavior but works well. another question is can we have a S7 class object to be a property of another S7 class object? seems the getClass() function doesn't work with S7 class object.

**Comment by hadley** [comment]
Yes, see https://rconsortium.github.io/OOP-WG/reference/as_class.html for details.
