### ISSUE TITLE
Compatibility with GitHub Actions workflow

### ISSUE THREAD

**Issue by nanxstats** [RConsortium/OOP-WG#285]
The standard `R CMD check` GitHub Actions workflow cannot find S7 even if it is listed in `Remotes`:

```
Error: 
! error in pak subprocess
Caused by error: 
! Could not solve package dependencies:
* deps::.: Can't install dependency S7 (>= 0.0.0.9000)
* S7: Can't find package called S7.
```

Example run: https://github.com/nanxstats/s7demo/actions/runs/4429064576/jobs/7769016620

Steps to create the test repo:

```r
usethis::create_package("s7demo/")
usethis::use_dev_package("S7", remote = "RConsortium/OOP-WG")
usethis::use_github_action_check_standard()
```

Perhaps because the repo name doesn't match the package name?

**Comment by remlapmot** [comment]
When the package name doesn't match the repo name, I think you can use **pkgdepends** syntax in Remotes, as described at <https://r-lib.github.io/pkgdepends/reference/pkg_refs.html#github-packages-github->

So you can probably specify it like this
```
Remotes:
    S7=RConsortium/OOP-WG
```

**Comment by nanxstats** [comment]
@remlapmot That works! Thanks so much. I'm closing this.
