### ISSUE TITLE
Additional requirement: reflection

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#3]
I'd like to propose one additional major requirement:

> 6. The system should be reflective
>
> Given a class and a generic, you should be able to find the appropriate method without calling it. This is important for building tooling around the system.

**Comment by lawremi** [comment]
Sure, please add it to the wiki page.

**Comment by hadley** [comment]
How about moving the requirements to regular files? Then you can do PRs and it feels a little more collaborative.

**Comment by lawremi** [comment]
If others prefer that, sure. I thought putting on the wiki would minimize the barrier to entry but perhaps people don't feel comfortable making unilateral edits.
