### ISSUE TITLE
Documentation on exporting methods from packages?

### ISSUE THREAD

**Issue by nerskin** [RConsortium/OOP-WG#306]
I have defined an S7 class in a package and exported it, but I can't see any documentation on how to also export the methods that I defined for the class. 

More concretely, if I have an S3 class called `new_class` and I want to define a print method and export it from my package, all I have to do is include 

```
print.new_class <- function(x) {
    #some code
}
```

in one of the R files, and add 

```
S3method(print,new_class)
```

to the NAMESPACE, but it's not currently clear (to me - apologies if I'm missing something obvious!) how to do the same for an S7 class

**Comment by hadley** [comment]
Unless I'm forgetting something, I don't think you need to do anything. Are you seeing problems?

**Comment by lawremi** [comment]
I guess what @nerskin is pointing out is the lack of documentation. There is no treatment of namespaces and exports in the vignettes, based on a quick inspection.

**Comment by nerskin** [comment]
Well it was partly to point out the lack of documentation and partly because I actually couldn't figure out how to do it. But there doesn't actually seem to be much to document, since I see now that if you export the class itself and the generic, then things Just Work. 

My confusion came about because I couldn't use the `print` method for my class after loading my package because I missed the bit in the generics and methods vignette about needing to use `new_external_generic` and include 

```
.onLoad <- function(libname, pkgname) {
  S7::external_methods_register()
}
```

when registering a method for a generic defined in another package. Instead of realising that it was an issue with using an external generic I assumed I was missing something from my NAMESPACE and went looking for documentation on that, finding none. I'm not sure if this is just me being foolish or something that's likely to trap other people!

**Comment by hadley** [comment]
This seems likely to catch other folks, so I think it's worth having a vignette about S7 in packages, even if it's very short.

**Comment by hadley** [comment]
Hmmmm, maybe I spoke to soon. The existing automatic mechanism works nicely for S7 generics (including external), but it would be nice if it also worked automatically for S3 and S4 methods too.

**Comment by hadley** [comment]
Ok, all works automatically now and we recommend all S7-using packages run the following code to dynamically register all needed methods:

```R
.onLoad <- function(libname, pkgname) {
  S7::methods_register()
}
```

(We may want to tweak the method registration process at some point in the future, but I think this setup is pretty elegant and easy to change if we come up with something better)
