### ISSUE TITLE
Error: 'S4SXP': should not happen - please report

### ISSUE THREAD

**Issue by marberts** [RConsortium/OOP-WG#318]
I was playing around with S7 and got a strange warning.

```r
> library(S7)

> test <- new_class("test", properties = list(x = class_any))

> y <- vector("list", 2)
> y[] <- test(x = 1)
Warning message:
Error: 'S4SXP': should not happen - please report
In addition: Lost warning messages

> y
[[1]]
<test>
 @ x: num 1

[[2]]
<test>
 @ x: num 1

```

I realize this isn't good practice (the RHS should be wrapped in a list) but the warning is weird and says to report. I can't get a traceback when turning the warning into an error (Error: no more error handlers available (recursive errors?); invoking 'abort' restart). The warning is coming from base R in `main/deparse.c`, and unfortunately this goes beyond my knowledge of R. I'm not sure if this is an S7 issue, or something deeper in base R.

Despite the origin of the strange warning, does it make sense to allow this kind of sub assignment? It's deprecated for S4.

```r
> test <- setClass("test", slots = c(x = "ANY"))

> y[] <- test(x = 1)
Warning message:
In `[<-`(`*tmp*`, , value = new("test", x = 1)) :
  implicit list embedding of S4 objects is deprecated

> y
[[1]]
An object of class "test"
Slot "x":
[1] 1


[[2]]
An object of class "test"
Slot "x":
[1] 1


```

And definitely doesn't make sense for S3.

```r
> test <- function(x) {
+   structure(list(x = x), class = "test")
+ }

> y[] <- test(x = 1)
> y
[[1]]
[1] 1

[[2]]
[1] 1
```

If it makes sense for an S7 object then it's probably worth getting rid of the warning; otherwise, a more sensible warning/error message would be helpful.

S7 0.0.0.9000
R 4.3.1
Ubuntu 20.04

**Comment by hadley** [comment]
@t-kalinowski is this fixed in your patch to R?

**Comment by t-kalinowski** [comment]
Yes, this should be fixed once https://github.com/r-devel/r-svn/pull/128 has been merged.
