### ISSUE TITLE
Uniqueness of class objects

### ISSUE THREAD

**Issue by lawremi** [RConsortium/OOP-WG#33]
If I have two class objects of the same name:
```
A1 <- newClass("A")
A2 <- newClass("A")
```

And defined a method for `A1`:
```
method(mean, A1) <- function(x) 10
```

How would dispatch react to passing an instance of `A2`?
```
mean(A2())
```

Does each call to `newClass()` do something like allocate a UUID that persists for the lifetime of the object? At the very least we would want to capture the calling environment (package namespace) to distinguish classes of the same name in different packages.

**Comment by hadley** [comment]
I think it has to create some sort of UUID; the `class` argument is purely informative.

It's also worth thinking about whether this would work:

```R
method(mean, "A") <- function(x) 10
```

And if so, what does it do?

**Comment by lawremi** [comment]
Do you have a good use case in mind for that? At least when following conventions, it should be straightforward to get the class object with `get()`.

**Comment by hadley** [comment]
Yeah but in your scenario above there’s no object called A — so I assume that would just be an error?

**Comment by lawremi** [comment]
To clarify, I was suggesting that `method()` only accept class objects, and that the user would call `get()` or something similar, likely in some metaprogramming situation. I guess the real question is whether it would ever be necessary to get a class by its name, instead of just looking it up under its symbol name (which should be the same, by convention). The overall intent is to keep things simple by not introducing another lookup table.

**Comment by hadley** [comment]
Ah, got it — so method would error when giving anything other than a class object?

I think there's one scenario where we might want to take a string:

```R
method(mean, "pkg::A") <- function(x) 10
```

This would be shorthand for something like:

```R
if (isNamespaceLoaded("pkg")) {
  method(generic, getExportedValue(pkg, class)) <- value
}

setHook(
  packageEvent(package, "onLoad"),
  function(...) {
    method(generic, getExportedValue(pkg, class)) <- value
  }
)
```

which would make it easy to register methods for suggested packages.

OTOH it might be more general to create a base helper that runs code when a package is loaded, and then you'd just do:

```R
whenLoaded("pkg", {
  method(mean, pkg::A) <- function() 10
  method(sum, pkg::A) <- function() 5
})
```

That would make the semantics of `method<-` simpler.

**Comment by lawremi** [comment]
I like the `whenLoaded()` idea, especially because it's outside of our scope ;)

**Comment by hadley** [comment]
It does imply dynamic registration of methods after package load, which currently works for S3 but (as far as I can tell) not for S4. So there's a small part in scope about making sure data isn't recorded in packages environments that get locked.

**Comment by hadley** [comment]
Closing because I think these ideas are now all noted in the design doc
