### ISSUE TITLE
Working name for this system

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#38]
What should we call it? At least for internal discussions.

**Comment by lawremi** [comment]
Current leading suggestion (from Hadley): S7

Pros: 
 - Cleverly acknowledges derivation from S3 and S4
 - Short and sweet
Cons: 
 - Purpose would not be obvious to anyone not well versed in R
 - The S[N++] arms race has caused some confusion in the past. It would be annoying if someone made an S8.

**Comment by hongooi73** [comment]
Torch now has R7, so it may be necessary to move to S8....

**Comment by dfalbel** [comment]
R7 is completely internal to torch and we don't plan to export it. I can rename to anything else if you think that it can cause confusion.

**Comment by mmaechler** [comment]
I like "R7"

**Comment by hadley** [comment]
I like R7 too.
