### ISSUE TITLE
Merging property values

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#42]
@lawremi I extracted this paragraph from the design doc because it no longer seems to fit where it was, and I don't understand it enough to integrate elsewhere:

The second step, merging property values, is also useful for updating an object (immutably, so returning a new object). This corresponds to the methods::initialize(), which also runs the validator. We would separate the (re)initialization from validation. This would allow the developer to update the object in controlled situations without triggering potentially expensive or redundant validation. If we implement initialization through a generic, the developer can override it for a particular class.

**Comment by lawremi** [comment]
Fine to remove that. It's mostly just me thinking in text. Allowing users to override the initialization (what happens inside `newObject()`) would probably just open the door to problems.
