### ISSUE TITLE
defineClass arguments

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#47]
Any objections to changing from:

```R
defineClass(
  name, 
  parent = object, 
  constructor = function(...) newObject(...), 
  validity = function(object) NULL,
  properties = list()
)
```

to 

```R
defineClass(
  name, 
  parent = Object, 
  constructor = function(...) newObject(...), 
  validator = function(x) NULL,
  properties = list()
)
```

i.e. renaming `validity` to `validator` (to match `constructor`) and changing the argument to `x` (since it's shorter but I think still conveys genericity).

**Comment by lawremi** [comment]
Seems fine to me (the original version was directly taken from the methods package). Btw, it's now called `newClass()` right?

**Comment by hadley** [comment]
Good point. I'll make the change.
