### ISSUE TITLE
Prefix class name with package

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#48]
For backward compatibility with S3, we need to generate a character class vector. If we use just the class name for this vector, we are implicitly using the name as an identifier for S3 dispatch. Is this something we need to worry about?

In other words, are we worried that pkgA defines `newClass("A")` and pkgB defines `newClass("A")`, and while dispatch in the new system can disambiguate, S3 dispatch does not?

**Comment by lawremi** [comment]
I assume you mean that both packages call `newClass("A")`. A potential hiccup in the transition will be that two packages that are currently instantiating the same type of object by convention will now need to agree on who defines the class.

**Comment by hadley** [comment]
(oops yes, fixed)

**Comment by hadley** [comment]
I started down the path of unconditionally prefixing the class name with the package name, but I'm concerned that going to be a pain because it also affects the S3 class name and depending on whether or not you're working interactively, the package name might not be detected correctly and so the class will vary. I think it'll be better to instead store as an attribute of the class and then only use for registration/dispatch. And then I think it makes sense to do after #137.

**Comment by hadley** [comment]
Thinking about this more, I think trying to do this automatically is going to be too fragile — it's too hard to reliably intuit the package name in every situation, which means it might vary during the development process. I think it's better to just document that exported classes should include the package name as a prefix, and suggest `package::class` as a convention.

**Comment by lawremi** [comment]
So would the convention be that the exported class object would be named `class` but the name of the class would be `package::class`? Could the "package::" prefix be added automatically during class definition if called from the package namespace?

**Comment by hadley** [comment]
@lawremi Yeah, so the object would be called `class` (or `package::class` if you were being explicit), and the class name would be `package::class`.

I don't think we can automatically add a `package::` prefix because:

* During development (where you might execute `new_class()` in the global environment) you'd get a different class, which seems like to introduce confusion. It's possible this all comes out in the wash (assuming you only use R7 functions to work with the object) but it makes me nervous.
* We lose the ability to use `::` vs `:::` to distinguish imported vs exported classes (this is a relatively small benefit, but it seems like a useful idea to me)

**Comment by hadley** [comment]
For now, I think I'll split the difference and add a `package` argument that defaults to `NULL`, and we'll strongly recommend you set it if you are including the class in a package. As well as adding a prefix to the class name used for dispatch, I think this will also affect serialisation. We'll need to talk this through in a future meeting, but I think if a class is registered as belonging to a package, when you serialise it we'll just serialise the name of the constructor function, rather than the constructor itself (as happens currently). We'll need to work through the consequences of this if the class definition changes, but I think your experience with S4 can guide us here.
