### ISSUE TITLE
Guidance for migrating to the new system

### ISSUE THREAD

**Issue by wlandau** [RConsortium/OOP-WG#52]
I think we are far along enough in the design to elaborate on what the transition will look like for the community, i.e. when to leave an existing project alone and when to extensively refactor. This may require expanding the [compatibility section of the design doc](https://github.com/RConsortium/OOP-WG/blob/master/spec/design.md#compatibility).

**Comment by wlandau-lilly** [comment]
Depends on #53.

**Comment by wlandau** [comment]
Depends on #53.

**Comment by hadley** [comment]
Closing this for now since we're still some ways from needing this.
