### ISSUE TITLE
Be precise about compatibility

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#53]
I think these are the 12 possible types of compatibility.

Inheritance:

* R7 extends S3 object: yes
* R7 extends S4 object: no?
* S3 extends R7 object: yes, to support incremental replacement of base classes.
* S4 extends R7 object: yes, via S3.

Composition:

* R7 has S3 property: yes
* R7 has S4 property: no
* S3 has R7 attribute: yes, because no restrictions
* S4 has R7 slot: yes, via S3

Methods:

* R7 generic + S3 object: yes
* R7 generic + S4 object: no?
* S3 generic + R7 object: yes
* S4 generic + R7 object: yes, via S3 

---

I think we can get away with not supporting S4 in R7 as long as we assume that any S4 -> R7 conversion proceeds from the inside out (i.e. start with the base class and it propagates out over time)

**Comment by lawremi** [comment]
R7 generics should be able to operate on S4 objects, as S3 generics do now. The link is essentially `extends(class(x))`, which returns an S3-style class vector for an S4 object. In principle, that could also help enable R7 classes extending S4 classes, but it would likely take some deep changes to the methods package.

Related thought: are we going to allow S4SXP instances of R7 classes, i.e., objects that just contain attributes, without being a list or whatever?
