### ISSUE TITLE
Method call frame

### ISSUE THREAD

**Issue by wlandau** [RConsortium/OOP-WG#56]
The [dispatch document](https://github.com/RConsortium/OOP-WG/blob/master/spec/dispatch.md#method-call-frame) proposes a possible alternative to `UseMethod()` that acts like an ordinary function call. What would it take to implement this without call frame issues? cc @lionel-.

I understand that maybe we want parent frames to agree if we want `deparse(substitute(arg))` to work (or if the user just wants to get the parent frame from inside a method). Seems like we could somehow make the actual call frames agree as well. Current S3 behavior:

```r
foo <- function(x, y)  {
  print(environment())
  print(parent.frame())
  UseMethod("foo")
}
foo.numeric <- function(x, y) {
  print(environment())
  print(parent.frame())
}
foo(1, 1)
#> <environment: 0x7fa55a559e60>
#> <environment: R_GlobalEnv>
#> <environment: 0x7fa55a551518>
#> <environment: R_GlobalEnv>
```

Goal for R7?

```r
foo <- function(x, y)  {
  print(environment())
  print(parent.frame())
  use_r7_method("foo")
}
foo.numeric <- function(x, y) {
  print(environment())
  print(parent.frame())
}
foo(1, 1)
#> <environment: 0x7fa55a559e60>
#> <environment: R_GlobalEnv>
#> <environment: 0x7fa55a559e60>
#> <environment: R_GlobalEnv>
```

I think these same considerations apply to `NextMethod()` and its possible alternatives.

**Comment by lawremi** [comment]
What would be the concrete benefits? There are some potential issues, for example, a non-trivial/standard generic might define some variables that would mysteriously show up in the method frame.

**Comment by hadley** [comment]
I don't think we need to use the same call frame; we're just likely to need some tricks to pass along unevaluated promises in such a way that `substitute()` in the method returns the same result that you'd get if it was evaluated in the generic.

**Comment by hadley** [comment]
Just to make this a bit more concrete, I think that this is the main challenge:

``` r
foo <- function(x) {
  UseMethod("foo")
}
foo.numeric <- function(x) {
  substitute(x)
}

x <- 1:10
foo(x)
#> x
```

<sup>Created on 2020-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Because this feature is used by important base functions like `plot()`.

**Comment by lawremi** [comment]
Agreed, that's an issue. In Bioconductor, we've had to rely on a hack to follow the promise chain in order to get the right frame for deferred evaluation, such as with `subset,DataFrame()`. I think the tidyverse has something similar.

**Comment by hadley** [comment]
@lawremi we've mostly moved to explicitly reifying promises into quosures (expr + env) and requiring special syntax to pass along to subcalls. I don't think that's a good fit with base R, but I'm sure we can come up with something.

**Comment by wlandau** [comment]
I also agree that unevaluated promises are an issue, but I am still not entirely convinced that we can live with disagreeing call frames. I feel as though there may be specialized use cases that require the user to directly call `environment()` and expect it to have whatever the generic and parent methods provide. This could easily come up with `lme4` workflows (ref: https://github.com/wlandau/targets/issues/160). Here is an example where I expect the generic and the method to return the same results.

``` r
print_quick_summary <- function(fit) {
  print(mean(coef(fit)$Subject$Days))
}

model <- function(data)  {
  data$Days <- -data$Days
  print_quick_summary(lmer(Reaction ~ Days + (Days | Subject), data = data))
  UseMethod("model")
}

model.data.frame <- function(data) {
  print_quick_summary(lmer(Reaction ~ Days + (Days | Subject), data = data))
}

library(lme4)
#> Loading required package: Matrix
library(tibble)
data <- new_tibble(sleepstudy, nrow = nrow(sleepstudy))
model(sleepstudy)
#> [1] -10.46729
#> [1] 10.46729
```

<sup>Created on 2020-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
> for example, a non-trivial/standard generic might define some variables that would mysteriously show up in the method frame.

But that's a good point, especially if the user does not define the generic.

**Comment by hadley** [comment]
I believe you could use `parent.frame(2)` to get the parent frame of the generic, since the `parent.frame()` of the method would always be the generic.

**Comment by wlandau** [comment]
True. 

How much do we care about call frame agreement among inherited methods? Seems like those are more likely to be user-defined.

```r
foo <- function(x) {
  print(parent.frame(2))
  print(environment())
  UseMethod("foo")
}
foo.x <- function(x) {
  print(parent.frame(2))
  print(environment())
  NextMethod()
}
foo.y <- function(x) {
  print(parent.frame(2))
  print(environment())
}
x <- structure(list(), class = c("x", "y"))
foo(x)
#> <environment: R_GlobalEnv>
#> <environment: 0x7fc7bc3b3b70>
#> <environment: R_GlobalEnv>
#> <environment: 0x7fc7bc3b7f98>
#> <environment: R_GlobalEnv>
#> <environment: 0x7fc7bc3be200>
```

**Comment by lawremi** [comment]
> I believe you could use `parent.frame(2)` to get the parent frame of the generic, since the `parent.frame()` of the method would always be the generic.

Except in the case of calls to the "next" method.

**Comment by wlandau** [comment]
Yes, child methods can get the frame of the generic but not the frames of the parents.

**Comment by hadley** [comment]
@lawremi ah true. In that case, though I'd probably suggest it's time to make the environment an explicit argument to the generic.
