### ISSUE TITLE
`method<-` complications

### ISSUE THREAD

**Issue by jimhester** [RConsortium/OOP-WG#57]
The proposed method definition syntax unfortunately throws a error at eval time

``` r
`method<-` <- function(generic, class, value) {
  str(substitute(generic))
  str(generic)
  registerS3method(generic, class, value, envir = parent.frame())
}

method("mean", "numeric") <- function(x) 1
#> Error in method("mean", "numeric") <- function(x) 1: target of assignment expands to non-language object
```

This is because the first argument is not a language object. We could work around this by either defining a dummy language object

``` r
`method<-` <- function(dummy, generic, class, value) {
  registerS3method(generic, class, value, envir = parent.frame())
}

. <- NULL
method(., "mean", "numeric") <- function(x) 1
mean(5)
#> [1] 1
```

or by passing the generic function directly.

``` r
`method<-` <- function(generic, class, value) {
  str(substitute(generic))
  str(generic)
  registerS3method(generic, class, value, envir = parent.frame())
}

method(mean, "numeric") <- function(x) 1
#>  symbol *tmp*
#> function (x, ...)
#> Error in match(x, table, nomatch = 0L): 'match' requires vector arguments
```

The main problem with the latter is as you can see we no longer have access to the name, even through `substitute()` because of the intermediate `*tmp*` variable used in `fun<-` assignments.

A third alternative would be to use `method["mean", "numeric"] <- function`, which would work, though it looks somewhat odd.

``` r
method <- structure(list(), class = "method_definitions")

`[<-.method_definitions` <- function(x, generic, class, value) {
  registerS3method(generic, class, value, envir = parent.frame())
}

method["mean", "numeric"] <- function(x) 1

mean(5)
#> [1] 1
```

**Comment by lawremi** [comment]
I think it's within our design specs to be able to introspect the name of a generic function, so we could support passing the generic directly, if introspection is feasible.

**Comment by hadley** [comment]
Except that we still have to be support delayed registration, when the generic isn't yet available.

**Comment by lawremi** [comment]
Perhaps we need something like C's `extern` keyword for declaring an eventual generic without defining it.

**Comment by jimhester** [comment]
As mentioned today using the generic object explicitly rather than passing a character vector and looking up the generic avoids these issues and we can use `method(foo, "blah") <-` syntax, so I am going to close this.
