### ISSUE TITLE
R CMD check issues with using `@`

### ISSUE THREAD

**Issue by jimhester** [RConsortium/OOP-WG#58]
Concretely, if I comment out the call to `globalVariables()` in https://github.com/RConsortium/OOP-WG/blob/a96f7e02a1bc2f12a445d25b6e0b5efcb91bebf3/R/zzz.R#L41

I get the following result from `R CMD check`

```
N  checking R code for possible problems (2.8s)
   method_register: no visible binding for global variable ‘name’
     (/private/var/folders/9x/_8jnmxwj3rq1t90mlr6_0k1w0000gn/T/Rtmpl5QIrn/R
7.Rcheck/00_pkg_src/R7/R/method.R:15)
   object_new: no visible binding for global variable ‘parent’
     (/private/var/folders/9x/_8jnmxwj3rq1t90mlr6_0k1w0000gn/T/Rtmpl5QIrn/R
7.Rcheck/00_pkg_src/R7/R/object.R:13)
   object_new: no visible binding for global variable ‘constructor’
     (/private/var/folders/9x/_8jnmxwj3rq1t90mlr6_0k1w0000gn/T/Rtmpl5QIrn/R
7.Rcheck/00_pkg_src/R7/R/object.R:13)
   print.r7_object: no visible binding for global variable ‘name’
     (/private/var/folders/9x/_8jnmxwj3rq1t90mlr6_0k1w0000gn/T/Rtmpl5QIrn/R
7.Rcheck/00_pkg_src/R7/R/class.R:43)
   Undefined global functions or variables:
     constructor name parent
```

It seems this is partially the result of needing to redefine `@` in R7. If `@` was generic like `@<-` or `$` we could just define a `@.r7_object` method and avoid this.

I am still tracking down where the filtering is happening in `codetools`, to see if there is another way we could avoid this.

**Comment by jimhester** [comment]
I think probably just adding "@" along with the existing "@<-" at https://gitlab.com/luke-tierney/codetools/-/blob/master/R/codetools.R#L298 would be sufficient to avoid this. It seems the reason that `@` calls are not normally flagged as globals is because `@` is defined in the base environment.

**Comment by jimhester** [comment]
I guess another way to address this would be to do what is done with [reference classes](https://github.com/wch/r-source/blob/8abcc2accc12893a6f14f0a775665d7849ebf785/src/library/methods/R/refClass.R#L1163-L1168) and automatically add the properties as global variables when declaring an R7 class.

**Comment by ltierney** [comment]
Getting `codetools` to handle `@` like `$` is the right thing to do. Feel free to post a merge request on GItLab. I probably won't have time to do the revdep checks for a while though.

**Comment by jimhester** [comment]
I opened one at https://gitlab.com/luke-tierney/codetools/-/merge_requests/1, happy to discuss more there if needed.
