### ISSUE TITLE
Method validation?

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#6]
Should we consider method validation to be a requirement of the system? i.e on method creation should we validate that the arguments are compatible with the generic? (this is currently performed by `R CMD check`, but making the error closer to definition might be useful)

Similarly, should we enforce who is allowed to define methods? As generally, you should only define a method if you "own" either the generic or the class. We could enforce this by only permitting method definition if the class or generic exists in the current package (this is a fairly narrow definition of ownership).

**Comment by lawremi** [comment]
Yes, we should validate generic/method consistency in their formals. No, we should not enforce who is allowed to define methods, as that would sacrifice a lot of the extensibility of functional OOP. Of course, third party methods should avoid making too many assumptions, so we should think of ways to help them stay independent of the class implementation.

**Comment by lionel-** [comment]
In the case of single dispatch, what would be a valid use case for a package to define methods when they don't own either the generic or the class? Given that registration affects every user of a generic, including the actual owner of the class, it would make sense to discourage it. Note that it would still be possible to work around it by registering from the global env (which would be allowed because the R user should be free to do what they want). The goal would be for packages to really go out of their way to perform unhygienic registration.

For double dispatch this would be harder to control. The authors of both classes should coordinate on the implementation, but it isn't clear there's a convenient way of determining that they have.

**Comment by lawremi** [comment]
The first example that comes to mind is plyranges. It takes an API defined by dplyr and makes it work on Bioconductor data structures. Third party adapters are common in object-oriented programming. This is a similar problem to symbol conflicts and probably motivated `importMethodsFrom()`, but there is no equivalent mechanism to `::` outside of a namespace. I've personally never encountered this problem though.

**Comment by lionel-** [comment]
This seems like a valid use case, though I would think the plyranges package needs to be blessed in some form by Bioconductor. First come first served does not seem like a desirable principle for method ownership. This is different from grabbing a public namespace.

As a counter-example, imagine someone decides to implement `print.formula()` to add colour escapes to highlight the tilde, and perhaps also `c.formula()` to make it more convenient to combine model formulas with `+`. Registering these methods in a package causes side effects for the whole ecosystem as soon as the package is loaded.

I agree this is not a common problem, so perhaps not worth worrying about. The more common problem with S3 was when two packages created a class with the same name and then competed for the implementation of third party methods. This problem would go away with namespaced classes.

**Comment by ltierney** [comment]
@lawremi:In the `plyranges` example Bioconductor owns the data structures. Not in a single package but as an organization. If a third  party comes in then @lionel- 's concerns apply. Not necessarily a show-stopper, but a reason for concern.

**Comment by hadley** [comment]
I think this discussion is now resolved:

* `methods<-` will check that the method is compatible with the generic
* `methods<-` will not check that you "own" either the class or the generic, but we will strongly emphasise that this is best practice in the documentation.

**Comment by lawremi** [comment]
Should we stick that in the requirements and/or design? Btw I think it's singular: `method<-`.

**Comment by hadley** [comment]
I'll add it to #35.
