### ISSUE TITLE
The syntax is sometimes inconsistent

### ISSUE THREAD

**Issue by cosi1** [RConsortium/OOP-WG#66]
For example, class/function names sometimes *have* to be quoted, sometimes *can't* be quoted,
and sometimes can, but don't have to be quoted – in the latter case, I'm not sure if using it
incorrectly will not cause an error further down the road.

**Comment by lawremi** [comment]
Would you please provide some concrete examples of this?

**Comment by jimhester** [comment]
In general all classes should be objects, except the base classes, e.g. `character`, `integer` etc.

**Comment by cosi1** [comment]
@lawremi (I dug it up from my notes, I'm not sure how correct it is.)

```{r}
R7::method(method_name_without_quotes, "class_name_with_quotes")

# whereas

R7::new_class(
  "class_name_with_quotes",
  parent = class_name_without_quotes  # !!!
)
```

**Comment by lawremi** [comment]
Seems like the method signature could be expressed using actual class objects (with the current caveat mentioned above). The class name passed to `new_class()` is a name, not a class, so I think it makes sense for it to be a character vector.
