### ISSUE TITLE
Should vectors extend common vector type?

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#77]
So that (e.g.) you could define a method that worked on all vectors.

**Comment by lawremi** [comment]
You can find it easily through reflection, i.e., `getClass()`.

**Comment by hadley** [comment]
Hmmm, that seems a bit too broad:

``` r
getClass("integer")
#> Class "integer" [package "methods"]
#> 
#> No Slots, prototype of class "integer"
#> 
#> Extends: 
#> Class "double", directly, with explicit coerce
#> Class "numeric", directly
#> Class "vector", directly
#> Class "data.frameRowLabels", directly
#> 
#> Known Subclasses: 
#> Class "factor", from data part
#> Class "ordered", by class "factor", distance 2
```

<sup>Created on 2021-11-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Maybe we should instead match the "implicit class" (e.g. [`sloop::s3_class()`](https://github.com/r-lib/sloop/blob/main/R/s3_class.R) or `.class2()`) with the additional of an atomic vector and vector union?

Per #94, I think the best way to implement these would be via class unions, so concretely, I'm suggesting that we add three class unions:

* `numeric <- new_union("integer", "double")`
* `atomic <- new_union("logical", numeric, "character", "raw", "complex")`
* `vector <- new_union(atomic, "list", "expression"))`

And then ensure that that R7 dispatch using implicit class names rather than typeof strings where they differ, i.e.:

```R
base_class <- function(x) {
  type <- typeof(x)
  switch(type,
    language = "call",
    closure = ,
    builtin = ,
    special = "function",
    symbol = "name",
    type
  )
}
```

Let's discuss the "virtual" matrix and array classes separately to keep this discussion scoped.

**Comment by hadley** [comment]
Note that we probably don't want to use `class()`/`.class2()` to avoid this:

``` r
.class2(quote(a <- b))
#> [1] "<-"
class(quote(a <- b))
#> [1] "<-"
```

<sup>Created on 2021-11-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

This makes R7 less compatible with S3 but I think this feature is so rarely used/understood that it's worth eliminating it to simplify the overall picture.
