### ISSUE TITLE
method<- should fail silently if external generic doesn't exist

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#86]
``` r
library(R7)

secret <- new_class("secret", parent = "character")
foo <- new_external_generic("pkgdown", "foo")
method(foo, "secret") <- function(x, ...) {}
#> Error in get(x, envir = ns, inherits = FALSE): object 'foo' not found
```

<sup>Created on 2021-10-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I think this makes it easier to use because you can define methods for generics that might only exist in the development version of another package, without having to worry about specifying an explicit package version.

**Comment by lawremi** [comment]
I like @jimhester 's idea of "declaring" an external generic, so the reader can always find the definition of a symbol. I think this was already discussed in a different issue.

**Comment by hadley** [comment]
@lawremi right, that's what we're doing above. But method registration fails if the generic doesn't turn out to exist (which it might not because the installed version of the package might be too old). I don't feel too strongly about this, so maybe it's just better to continue to require an explicit version.
