### ISSUE TITLE
Allow R7 objects in properties list?

### ISSUE THREAD

**Issue by hadley** [RConsortium/OOP-WG#91]
As a shortcut, instead of specifying the name of the class.

**Comment by lawremi** [comment]
Would that object automatically be part of the prototype of the class, i.e., the default value of the property?

**Comment by hadley** [comment]
I think so?

**Comment by hadley** [comment]
Superseded by the more general #120.

@lawremi I realised I meant R7 classes, not objects, so I don't think it's related to default values.
